version: 2
updates:
- package-ecosystem: nuget
  directory: "/ServiceBus.EnvPlugin"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Azure.ServiceBus
    versions:
    - 5.1.1
    - 5.1.2
- package-ecosystem: nuget
  directory: "/Sample/ServiceBus.Sample.Env"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Azure.ServiceBus
    versions:
    - 5.1.1
    - 5.1.2
- package-ecosystem: nuget
  directory: "/ServiceBus.EnvPluginTests"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Azure.ServiceBus
    versions:
    - 5.1.1
    - 5.1.2
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
